spring:
  datasource:
    url: jdbc:mysql://localhost:3306/moviebookingapp?createDatabaseIfNotExist=true
    username: root
    password: root
    
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL8Dialect
  application:
    name: movie-booking-service
security:
  oauth2:
    resource:
      token-info-uri: http://localhost:8091/oauth/check_token
    client:
      client-id: client
      client-secret: password
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8085
play:
  url: http://movie-inventory-service/play/
kafka:
  url: http://kafka-service/kafka/publish/
token:
  url: http://localhost:8091/oauth/token
auth:
  server:
     schema: http
logstash:
  host: localhost
  port: 5044